#!/usr/bin/env bash

set -eu

IMAGE=docker.io/deepprojects/camelyon-utils:0.2

docker build --pull -t ${IMAGE} .
docker run --rm -u 1000:1000 ${IMAGE} red-connector-http --version
docker run --rm -u 1000:1000 ${IMAGE} red-connector-ssh --version
docker run --rm -u 1000:1000 ${IMAGE} red-connector-xnat-http --version
docker run --rm -u 1000:1000 ${IMAGE} camelyon-utils --version
docker run --rm -u 1000:1000 ${IMAGE} camelyon-utils slide-tiles --help
docker run --rm -u 1000:1000 ${IMAGE} camelyon-utils merge-hdf5 --help
docker push ${IMAGE}
