#!/usr/bin/env bash

set -eu

IMAGE=docker.io/deepprojects/knime-labelfree-quantification:dev

docker build --pull -t ${IMAGE} .
docker run --rm -u 1000:1000 ${IMAGE} red-connector-http --version
docker run --rm -u 1000:1000 ${IMAGE} red-connector-http-archive --version
docker run --rm -u 1000:1000 ${IMAGE} red-connector-ssh --version
docker push ${IMAGE}
